"""empty message

Revision ID: 19ef32e9556f
Revises: 99c36af600c0
Create Date: 2018-02-02 11:57:39.643269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ef32e9556f'
down_revision = '99c36af600c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('filepath', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'filepath')
    # ### end Alembic commands ###
