"""empty message

Revision ID: 99c36af600c0
Revises: b9a747fd4208
Create Date: 2018-01-30 13:03:17.816621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c36af600c0'
down_revision = 'b9a747fd4208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disease_info', 'totalss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease_info', sa.Column('totalss', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
