"""empty message

Revision ID: b9a747fd4208
Revises: 
Create Date: 2018-01-30 13:01:03.986051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9a747fd4208'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease_info', sa.Column('totalss', sa.Integer(), nullable=True))
    op.drop_column('users', 'certificate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('certificate', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('disease_info', 'totalss')
    # ### end Alembic commands ###
